# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- sprint0

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
    python -m venv venv #this onwards is my addition, can be removed if it doesn't make sense
    . venv/bin/activate
    pip install -r requirements.txt
    python manage.py collectstatic --noinput
  displayName: 'Install dependencies and run collectstatic'
