# Generated by Django 5.0.2 on 2024-02-22 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourtType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('C', 'Clay'), ('G', 'Grass'), ('H', 'Hard')], default='C', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('court_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.courttype')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('court_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.court')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
