# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - msdocs-python-postgres-XXX

on:
  push:
    branches:
      - deployment
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Setup Node.js for React build
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Adjust as per your React project's requirements

      - name: Install and build React app
        run: |
          cd frontend # Adjust this if your React app is in a different directory
          npm install
          npm run build

      - name: Move React build to static files directory
        run: |
          mkdir -p static/react
          mv frontend/build/* static/react/

      - name: Collect static files
        run: |
          python manage.py collectstatic --noinput
      - name: List static files
        run: ls -R static/

      - name: Zip artifact for deployment
        run: zip -r release.zip ./* -x "venv/*"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AC93F41AAFE04304BA85410B76F65144 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7FAC043BDA1340EDBE63B9183971F50B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_14DCE2D8B8E14420A2F7C378FF4A9226 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'msdocs-python-postgres-XXX'
          slot-name: 'Production'
          