name: Build and deploy Node.js app to Azure Web App - cps2009project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install and build frontend
        run: |
          npm install
          npm run build
        working-directory: ./frontend

      - name: Move to server directory
        run: cd server
        
      - name: npm install and build for server
        run: |
          npm install
          npm run build --if-present
        working-directory: ./server

      - name: Run tests and save results
        run: |
          npm test > test-results.txt || true
        working-directory: ./server

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always() # This ensures that the artifact is uploaded even if the test step fails
        with:
          name: test-results
          path: ./server/test-results.txt
          
      - name: Copy frontend build to server's public directory
        run: |
          mkdir -p ./server/public
          cp -R ./frontend/build/* ./server/public/
      
      - name: Zip artifact for deployment
        run: zip -r ../release.zip ./*
        working-directory: ./server

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: confirm release.zip exists
        run: ls -al release.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'cps2009project'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0556A53FB51D4634AAADFD40A3A4A256 }}
          package: release.zip
