name: Build and deploy Node.js app to Azure Web App - cps2009project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Build frontend
        run: |
          npm install
          npm run build
        working-directory: ./frontend

      - name: Move frontend build to server directory
        run: mv frontend/build server/public

      - name: npm install and build server
        run: |
          npm install
          npm run build --if-present
        working-directory: ./server

      - name: Zip artifact for deployment
        run: zip -r ../release.zip ./*
        working-directory: ./server

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: ./server/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: confirm release.zip exists
        run: ls -al release.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'cps2009project'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0556A53FB51D4634AAADFD40A3A4A256 }}
          package: release.zip